// <auto-generated />
using System;
using Garage_2._0.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Garage_2._0.Migrations
{
    [DbContext(typeof(GarageContext))]
    [Migration("20251218091502_RemoveAutoValueFromArrivalTime")]
    partial class RemoveAutoValueFromArrivalTime
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Garage_2._0.Models.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ArrivalTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("NumberOfWheels")
                        .HasColumnType("int");

                    b.Property<string>("RegNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("VehicleType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Vehicle");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArrivalTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Brand = "Volvo",
                            Color = "Red",
                            Model = "V70",
                            NumberOfWheels = 4,
                            RegNumber = "ABC123",
                            VehicleType = 0
                        },
                        new
                        {
                            Id = 2,
                            ArrivalTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Brand = "East Marine",
                            Color = "Yellow",
                            Model = "Viking Line",
                            NumberOfWheels = 0,
                            RegNumber = "LGH436",
                            VehicleType = 4
                        },
                        new
                        {
                            Id = 3,
                            ArrivalTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Brand = "Volvo",
                            Color = "Red",
                            Model = "V7900",
                            NumberOfWheels = 8,
                            RegNumber = "AHC745",
                            VehicleType = 2
                        },
                        new
                        {
                            Id = 4,
                            ArrivalTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Brand = "Teesla",
                            Color = "White",
                            Model = "X",
                            NumberOfWheels = 4,
                            RegNumber = "KAK156",
                            VehicleType = 0
                        },
                        new
                        {
                            Id = 5,
                            ArrivalTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Brand = "Scania",
                            Color = "Blue",
                            Model = "G-series",
                            NumberOfWheels = 6,
                            RegNumber = "IKA71U",
                            VehicleType = 3
                        },
                        new
                        {
                            Id = 6,
                            ArrivalTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Brand = "Mercedez",
                            Color = "Green",
                            Model = "L420",
                            NumberOfWheels = 2,
                            RegNumber = "ÅJAUIV",
                            VehicleType = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
